version: '3'

services:
    postgres:
        image: 'postgres:latest'

    redis:
        image: 'redis:latest'

    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        depends_on: 
            - api
            - client
        restart: always
        ports: 
            - '3000:80'

    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        depends_on: 
            - postgres
            - redis
            - worker
        volumes:
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST
            - REDIS_PORT
            - PGHOST
            - PGPORT
            - PGUSER
            - PGPASSWORD
            - PGDATABASE

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app

    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        depends_on: 
            - redis
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST
            - REDIS_PORT